- name: deepseek-coder:6.7b
- name: deepseek-r1:8b
- name: gemma3:4b
- name: llama3.1:8b
- name: llava:7b
- name: ministral-3:8b
- name: mistral-nemo:12b
- name: mistral:7b
- name: phi3:3.8b
- name: qwen2.5-coder:7b
- name: qwen2.5:7b
- name: qwen2.5vl:7b
- name: qwen3-vl:8b
- name: qwen3:8b
- name: CognitiveComputations/dolphin-llama3.1:8b
- name: dolphin3:8b
- name: huihui_ai/deepseek-r1-abliterated:8b
- name: huihui_ai/dolphin3-abliterated:8b
- name: huihui_ai/gemma3-abliterated:4b
- name: huihui_ai/qwen2.5-abliterate:7b
- name: huihui_ai/qwen3-abliterated:8b
- name: huihui_ai/qwen3-vl-abliterated:8b